#!/usr/bin/env bash
# Runs on every Codespace start via devcontainer.json postStartCommand.
#
# Output lands in $REPO/.devcontainer/logs/start.log via an `exec`
# redirect. We do not also tee to stdout because postStartCommand runs
# non-interactively and its stdout is not shown anywhere prominent.
# The banner in stage 4 makes up for this by auto-catting bootstrap.log
# and start.log on the first interactive shell after each container
# start. Output is explicit echoes only, no `set -x`, so the dump
# stays inside the VS Code terminal scrollback budget.
#
# Six stages, each idempotent:
#   1. Clear the "first-shell log dump already shown" flag so the
#      next interactive shell gets a fresh one-shot dump if the app
#      is not running.
#   2. Self-heal: if neither prototype/.venv/bin/streamlit nor a system
#      streamlit on PATH exists, re-run .devcontainer/post_create.sh.
#   3. Refresh the Streamlit config in the user profile so port 8501
#      stays pinned even if the user tampered with ~/.streamlit/config.toml.
#   4. Write a terminal banner script to ~/.vbi_banner.sh. The banner
#      is written for non-technical workshop participants. It shows a
#      single state line ("your app is ready" or "the app is still
#      starting"), a numbered three-step instruction to open the app,
#      a plain-language Help block for the four most common issues,
#      and on the first shell after each container start, if the app
#      is not running, a 30-line tail of the streamlit log so the user
#      has something copy-pasteable to share with the LLM.
#   5. Ensure ~/.bashrc sources the banner file exactly once, and clean
#      up any legacy VBI_APP_URL_BANNER lines from earlier devcontainer
#      versions.
#   6. Launch Streamlit as a fully detached background process via
#      `nohup`. `( ... ) &` was not enough on its own: the
#      postStartCommand shell could send SIGHUP to its children on exit
#      and silently kill Streamlit right after launch. `nohup` ignores
#      SIGHUP, `&` puts it in the background, `disown` removes it from
#      the shell's job table, and `</dev/null` frees the controlling
#      terminal. Streamlit output goes to .devcontainer/logs/streamlit.log.

cd "$(dirname "$0")/.." || cd "${CODESPACE_VSCODE_FOLDER:-/workspaces/vibe-innovation-lab}"
mkdir -p .devcontainer/logs
exec > .devcontainer/logs/start.log 2>&1

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
VBI_REPO="$(pwd)"

echo "=== post_start.sh starting at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "cwd:  $VBI_REPO"
echo "PATH: $PATH"

# Stage 1: clear the first-shell flag so the next interactive shell
# gets a fresh log tail if the app is not running. Also clear legacy
# flag names from older devcontainer versions to avoid stale state
# after an update.
rm -f ~/.vbi_bootstrap_shown ~/.vbi_logs_shown /tmp/vbi_logs_shown 2>/dev/null || true

# Stage 2: self-heal. If no streamlit binary exists, re-run the full
# bootstrap. Last line of defence for a broken postCreateCommand.
if [ ! -x prototype/.venv/bin/streamlit ] && ! command -v streamlit >/dev/null 2>&1; then
    echo "post_start: no streamlit binary found, re-running post_create.sh"
    bash .devcontainer/post_create.sh || echo "post_start: post_create.sh failed, continuing anyway"
fi

# Stage 3: refresh Streamlit config.
mkdir -p ~/.streamlit
cp prototype/.streamlit/config.toml ~/.streamlit/config.toml || \
    echo "WARN: could not copy prototype/.streamlit/config.toml"

# Stage 4: write the banner file. Unquoted heredoc so _vbi_repo is
# interpolated at write time and baked into the banner. All other
# $-expressions are escaped with a backslash so they evaluate at shell
# source time, giving fresh state on every new interactive shell.
#
# Design goal: workshop-friendly for non-technical participants. One
# state line, one numbered open-the-app instruction, one plain-language
# help block, one discovery line for the curious. No component matrix,
# no command lists, no jargon. A broken-state log tail appears only on
# the first shell after each container start to give users a copy-
# pasteable error to share with the LLM.
cat > ~/.vbi_banner.sh << BANNEREOF
# Auto-generated by .devcontainer/post_start.sh. Do not edit by hand.
# Re-generated on every Codespace start. Baked workspace path: ${VBI_REPO}
_vbi_repo="${VBI_REPO}"
_vbi_url="https://\${CODESPACE_NAME}-8501.\${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

# Is the app actually listening on port 8501 right now? Fresh check
# on every new interactive shell, so reopening a terminal picks up a
# state change without a restart.
if timeout 1 bash -c "</dev/tcp/localhost/8501" 2>/dev/null; then
    _vbi_ready="yes"
else
    _vbi_ready="no"
fi

echo ""
echo "========================================================================"
if [ "\$_vbi_ready" = "yes" ]; then
    echo "  Vibe Innovation Lab: your app is ready"
else
    echo "  Vibe Innovation Lab: the app is still starting"
fi
echo "========================================================================"
echo ""

if [ "\$_vbi_ready" = "yes" ]; then
    echo "  How to open your app"
    echo ""
    echo "  1. Look at the bottom of VS Code for a tab called PORTS."
    echo "  2. Next to port 8501, click the small globe icon."
    echo "  3. The app opens in a new browser tab."
    echo ""
    echo "  Or paste this link into any browser tab you already have open:"
    echo ""
    echo "     \${_vbi_url}"
    echo ""
else
    echo "  The app is not ready yet. Give it 10 to 30 more seconds,"
    echo "  then open a new terminal. This banner updates on every new"
    echo "  terminal you open."
    echo ""
    echo "  App link (for when it is ready):"
    echo ""
    echo "     \${_vbi_url}"
    echo ""
fi

echo "  Help"
echo ""
echo "  1. The app does not open, or it shows an error in the browser."
echo "     Open the file .devcontainer/logs/streamlit.log in the file"
echo "     tree on the left. The last few lines show what went wrong."
echo "     Copy them and paste them into your conversation with the"
echo "     LLM. The LLM will fix it."
echo ""
echo "  2. You edited the code and the app did not update."
echo "     Scroll to the top of the app in the browser and click the"
echo "     \"Always rerun\" button. After that every save triggers a"
echo "     hot reload within a second."
echo ""
echo "  3. You want to start the prototype over."
echo "     Ask the LLM to rewrite the code. Paste the new code into"
echo "     prototype/app.py, replacing everything that was there."
echo ""
echo "  4. Nothing else worked."
echo "     Stop the Codespace from the menu at the top left of VS"
echo "     Code (three-line icon, Codespaces, Stop current Codespace),"
echo "     then start it again. Do not rebuild."
echo ""
echo "  Curious about what happened during setup? Run:"
echo "     cat .devcontainer/logs/bootstrap.log"
echo ""
echo "========================================================================"

# On the first shell after each container start, if the app is not
# ready, print the last 30 lines of the streamlit log so the user has
# something concrete to paste into their LLM conversation. Working
# state stays clean. The flag file is cleared by post_start.sh stage 1
# on every container start, so a restart gives a fresh one-shot dump.
if [ ! -f ~/.vbi_bootstrap_shown ] && [ "\$_vbi_ready" = "no" ]; then
    echo ""
    echo "  Last 30 lines from the app log (copy these to the LLM):"
    echo ""
    if [ -f "\${_vbi_repo}/.devcontainer/logs/streamlit.log" ]; then
        tail -n 30 "\${_vbi_repo}/.devcontainer/logs/streamlit.log" 2>/dev/null | sed 's/^/     /'
    else
        echo "     (no log file yet)"
    fi
    echo ""
    echo "========================================================================"
fi
touch ~/.vbi_bootstrap_shown 2>/dev/null || true

unset _vbi_url _vbi_ready
BANNEREOF

# Stage 5: ensure .bashrc sources the banner exactly once, and clean up
# any legacy single-line banner from earlier devcontainer versions.
if [ -f ~/.bashrc ]; then
    sed -i '/# VBI_APP_URL_BANNER/,+1d' ~/.bashrc
fi
grep -q 'source ~/.vbi_banner.sh' ~/.bashrc 2>/dev/null || echo 'source ~/.vbi_banner.sh' >> ~/.bashrc

# Stage 6: launch Streamlit as a fully detached background process.
echo "--- Streamlit auto-start at $(date -u +%Y-%m-%dT%H:%M:%SZ) ---" > .devcontainer/logs/streamlit.log
if [ -x prototype/.venv/bin/streamlit ]; then
    echo "launching via prototype/.venv/bin/streamlit" >> .devcontainer/logs/streamlit.log
    nohup bash -c "cd '$VBI_REPO/prototype' && exec .venv/bin/streamlit run app.py" \
        >> .devcontainer/logs/streamlit.log 2>&1 </dev/null &
    disown
elif command -v streamlit >/dev/null 2>&1; then
    echo "launching via system streamlit on PATH" >> .devcontainer/logs/streamlit.log
    nohup bash -c "cd '$VBI_REPO/prototype' && exec streamlit run app.py" \
        >> .devcontainer/logs/streamlit.log 2>&1 </dev/null &
    disown
else
    echo "no streamlit binary available, app will not start" >> .devcontainer/logs/streamlit.log
    echo "run: bash .devcontainer/post_create.sh" >> .devcontainer/logs/streamlit.log
fi

sleep 1
echo "=== post_start.sh finished at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "=== streamlit processes ==="
ps aux | grep -E 'streamlit|nohup' | grep -v grep || echo "no streamlit processes found"
exit 0
